In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import resample

In [2]:
data = pd.read_csv('Data-Collisions.csv')

F:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
data

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
...              ...         ...        ...       ...     ...        ...   
194668             2 -122.290826  47.565408    219543  309534     310814   
194669             1 -122.344526  47.690924    219544  309085     310365   
194670             2 -122.306689  47.683047    219545  311280     312640   
194671             2 -122.355317  47.678734    219546  309514     310794   
194672             1 -122.289360  47.611017    219547  308220     309500   

       REPORTNO   STATUS      ADDRTYPE   INTKEY  ... ROADCOND  \
0       3502005  Matched  Intersection  37475.0  ...      Wet   
1       2607959  Matched         Block      NaN  ...      Wet   
2       1482393  Matched         Block      NaN  ...      Dry   
3       3503937  Matched         Block      NaN  ...      Dry   
4       1807429  Matched  Intersection  34387.0  ...      Wet   
...         ...      ...           ...      ...  ...      ...   
194668  E871089  Matched         Block      NaN  ...      Dry   
194669  E876731  Matched         Block      NaN  ...      Wet   
194670  3809984  Matched  Intersection  24760.0  ...      Dry   
194671  3810083  Matched  Intersection  24349.0  ...      Dry   
194672  E868008  Matched         Block      NaN  ...      Wet   

                      LIGHTCOND PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0                      Daylight           NaN         NaN      NaN         10   
1       Dark - Street Lights On           NaN   6354039.0      NaN         11   
2                      Daylight           NaN   4323031.0      NaN         32   
3                      Daylight           NaN         NaN      NaN         23   
4                      Daylight           NaN   4028032.0      NaN         10   
...                         ...           ...         ...      ...        ...   
194668                 Daylight           NaN         NaN      NaN         24   
194669                 Daylight           NaN         NaN      NaN         13   
194670                 Daylight           NaN         NaN      NaN         28   
194671                     Dusk           NaN         NaN      NaN          5   
194672                 Daylight           NaN         NaN      NaN         14   

                                               ST_COLDESC  SEGLANEKEY  \
0                                       Entering at angle           0   
1       From same direction - both going straight - bo...           0   
2                                  One parked--one moving           0   
3                        From same direction - all others           0   
4                                       Entering at angle           0   
...                                                   ...         ...   
194668    From opposite direction - both moving - head-on           0   
194669  From same direction - both going straight - bo...           0   
194670  From opposite direction - one left turn - one ...           0   
194671                       Vehicle Strikes Pedalcyclist        4308   
194672  From same direction - both going straight - on...           0   

        CROSSWALKKEY  HITPARKEDCAR  
0                  0             N  
1                  0             N  
2                  0             N  
3                  0             N  
4                  0             N  
...              ...           ...  
194668             0             N  
194669             0             N  
194670             0             N  
194671             0             N  
194672             0             N  

[194673 rows x 38 c

In [ ]:
data.info()

In [4]:
project_df = data.loc[:,['SEVERITYCODE', 'WEATHER', 'ROADCOND', 'LIGHTCOND']]

In [6]:
project_df = project_df.dropna()

In [7]:
project_df

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
0                  2  Overcast      Wet                 Daylight
1                  1   Raining      Wet  Dark - Street Lights On
2                  1  Overcast      Dry                 Daylight
3                  1     Clear      Dry                 Daylight
4                  2   Raining      Wet                 Daylight
...              ...       ...      ...                      ...
194668             2     Clear      Dry                 Daylight
194669             1   Raining      Wet                 Daylight
194670             2     Clear      Dry                 Daylight
194671             2     Clear      Dry                     Dusk
194672             1     Clear      Wet                 Daylight

[189337 rows x 4 columns]

In [8]:
project_df['SEVERITYCODE'].value_counts()

1    132285
2     57052
Name: SEVERITYCODE, dtype: int64

In [9]:
project_df_1 = project_df[project_df['SEVERITYCODE'] == 1] = project_df[project_df['SEVERITYCODE'] == 1]
project_df_2 = project_df[project_df['SEVERITYCODE'] == 2]

In [10]:
project_df_1_dsample = resample(project_df_1, 
                                replace=False,
                                n_samples=57052,
                                random_state=123)

balanced_df = pd.concat([project_df_1_dsample, project_df_2])
balanced_df['SEVERITYCODE'].value_counts()

2    57052
1    57052
Name: SEVERITYCODE, dtype: int64

In [11]:
balanced_df

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
82770              1     Clear      Dry                 Daylight
122946             1     Clear      Dry                 Daylight
102968             1     Clear      Dry                 Daylight
13906              1  Overcast      Dry                 Daylight
123301             1   Raining      Wet  Dark - Street Lights On
...              ...       ...      ...                      ...
194663             2   Raining      Wet                 Daylight
194666             2     Clear      Wet                 Daylight
194668             2     Clear      Dry                 Daylight
194670             2     Clear      Dry                 Daylight
194671             2     Clear      Dry                     Dusk

[114104 rows x 4 columns]

In [12]:
balanced_df['WEATHER'] = pd.Categorical(balanced_df['WEATHER'])
balanced_df['WEATHER_CODE'] = balanced_df['WEATHER'].cat.codes

In [13]:
balanced_df['ROADCOND'] = pd.Categorical(balanced_df['ROADCOND'])
balanced_df['ROADCOND_CODE'] = balanced_df['ROADCOND'].cat.codes

In [14]:
balanced_df['LIGHTCOND'] = pd.Categorical(balanced_df['LIGHTCOND'])
balanced_df['LIGHTCOND_CODE'] = balanced_df['LIGHTCOND'].cat.codes

In [15]:
balanced_df

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND  \
82770              1     Clear      Dry                 Daylight   
122946             1     Clear      Dry                 Daylight   
102968             1     Clear      Dry                 Daylight   
13906              1  Overcast      Dry                 Daylight   
123301             1   Raining      Wet  Dark - Street Lights On   
...              ...       ...      ...                      ...   
194663             2   Raining      Wet                 Daylight   
194666             2     Clear      Wet                 Daylight   
194668             2     Clear      Dry                 Daylight   
194670             2     Clear      Dry                 Daylight   
194671             2     Clear      Dry                     Dusk   

        WEATHER_CODE  ROADCOND_CODE  LIGHTCOND_CODE  
82770              1              0               5  
122946             1              0               5  
102968             1              0               5  
13906              4              0               5  
123301             6              8               2  
...              ...            ...             ...  
194663             6              8               5  
194666             1              8               5  
194668             1              0               5  
194670             1              0               5  
194671             1              0               6  

[114104 rows x 7 columns]

--------------

In [ ]:
project_df['WEATHER'].value_counts()

In [ ]:
project_df['ROADCOND'].value_counts()

In [ ]:
project_df['LIGHTCOND'].value_counts()

--------

In [16]:
X = np.asarray(balanced_df[['WEATHER_CODE', 'ROADCOND_CODE', 'LIGHTCOND_CODE']])
X[0:5]

array([[1, 0, 5],
       [1, 0, 5],
       [1, 0, 5],
       [4, 0, 5],
       [6, 8, 2]], dtype=int8)

In [17]:
y = np.asarray(balanced_df['SEVERITYCODE'])
y[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [18]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.71907961, -0.69272349,  0.39316776],
       [-0.71907961, -0.69272349,  0.39316776],
       [-0.71907961, -0.69272349,  0.39316776],
       [ 0.39080216, -0.69272349,  0.39316776],
       [ 1.13072334,  1.5045195 , -1.43589428]])

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=45)

## KNN

In [20]:
from sklearn.neighbors import KNeighborsClassifier
k = 25
knn = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
knn_y_predict = knn.predict(X_test)
knn_y_predict[0:5]

array([2, 2, 2, 2, 1], dtype=int64)

In [21]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, knn_y_predict)

0.29647156115041806

In [22]:
from sklearn.metrics import f1_score
f1_score(y_test, knn_y_predict, average='macro')

0.538428479262381

## Decision Tree

In [23]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion="entropy", max_depth=7)
dt.fit(X_train, y_train)
dt_y_predict = dt.predict(X_test)

In [24]:
jaccard_score(y_test, dt_y_predict)

0.2573432060020595

In [25]:
f1_score(y_test, dt_y_predict, average='macro')

0.5278396614127413

## Linear Regression

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
lr = LogisticRegression(C=6, solver="liblinear").fit(X_train,y_train)
lr_y_predict = lr.predict(X_test)

In [27]:
jaccard_score(y_test, lr_y_predict)

0.2896912283837526

In [28]:
f1_score(y_test, lr_y_predict, average='macro')

0.5239236739141877